runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

endpoints_api_service:
  name: exterkamp-spotify-recents.appspot.com
  rollout_strategy: managed
