swagger: "2.0"
info:
  description: "A simple Google Cloud Endpoints API example."
  title: "Endpoints Example"
  version: "2.0.0"
host: "exterkamp-spotify-recents.appspot.com"

consumes:
- "application/json"
produces:
- "application/json"
schemes:
- "https"
paths:
  "/recents":
    get:
      description: "Gets top 3 recent tracks."
      operationId: "recent"
      produces:
      - "application/json"
      responses:
        200:
          description: "Get recents."
          schema:
            $ref: "#/definitions/spotifyTrackContainer"

definitions:
  spotifyTrackContainer:
    type: "object"
    properties:
      tracks:
        type: "array"
        items: 
          $ref: "#/definitions/spotifyTrack"
      update_time:
        type: "number"
  spotifyTrack:
    type: "object"
    properties:
      name:
        type: "string"
      preview_url:
        type: "string"
      spotify_url:
        type: "string"
      album_art_encoded:
        type: "string"
      album:
        type: "string"
      album_art_url:
        type: "string"
      artists:
        type: "array"
        items:
          type: "object"
          properties:
            name:
              type: "string"
